on:
  push:
    branches:
    - main

jobs:
  group:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "::group::group name"
      - run: echo "hoge1"
      - run: echo "hoge2"
      - run: echo "::endgroup::"
      - run: echo "fuga1"

  annotation:
    runs-on: ubuntu-latest

    steps:
      - run: echo "::error::something wrong"
      - run: echo "::warning::caution"
      - run: echo "::notice::information"
